### ISSUE TITLE
Can we add routing configuration to documentation?

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize_news#30]
For example, if you have calendarize list view and news detail, the URLs will be generated with "extra" index parameter, e.g.

`https://mysite/blah/event/my-title-2-5663?tx_news_pi1%5Bindex%5D=58536&cHash=afcc09bda2d3d0729271b2062ae2ce8d`

I had this configuration f. news (detail only here):

```
NewsDetail:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
    defaultController: 'News::detail'
    aspects:
      news_title:
        type: PersistedPatternMapper
        tableName: tx_news_domain_model_news
        routeFieldPattern: '^(?P<path_segment>.+)-(?P<uid>\d+)$'
        routeFieldResult: '{path_segment}-{uid}'
```

I added configuration for calendarize_news:

```
NewsDetail:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
      - routePath: '/{news_title}/{index}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
          calendarize_index: index
    defaultController: 'News::detail'
    aspects:
      news_title:
        type: PersistedPatternMapper
        tableName: tx_news_domain_model_news
        routeFieldPattern: '^(?P<path_segment>.+)-(?P<uid>\d+)$'
        routeFieldResult: '{path_segment}-{uid}'
      calendarize_index:
        type: PersistedAliasMapper
        tableName: tx_calendarize_domain_model_index
        routeFieldName: slug
```

Could someone check and confirm?

**Comment by sypets** [comment]
ok, solution above is not so great because it creates overly long URLs. 

`https://mysite/test/eventnews/news-detail/test-news-1-5756/test-news-1`

I am not sure if we need to pass the index but it looks like it in the controller action. Probably, it is only necessary to pass the index uid, but not the news uid (because news uid is in tx_calendarize_domain_model_index.foreign_uid). 

Working on improvement now ...

**Comment by sypets** [comment]
Anyway, changed it now to this which results in 2 numbers in URL, news uid and index uid. I am not so familiar with the details here so help would be appreciated. As mentioned, the index uid might suffice in the action.

`https://mysite/test/eventnews/news-detail/test-news-1-5756-8622`

  ```
NewsDetail:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
      -
        routePath: '/{news_title}-{index}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
          calendarize_index: index
    defaultController: 'News::detail'
    aspects:
      news_title:
        type: PersistedPatternMapper
        tableName: tx_news_domain_model_news
        routeFieldPattern: '^(?P<path_segment>.+)-(?P<uid>\d+)$'
        routeFieldResult: '{path_segment}-{uid}'
      calendarize_index:
        type: PersistedAliasMapper
        tableName: tx_calendarize_domain_model_index
        routeFieldName: uid
```
